export const LOAD_POSTS = {
  REQUEST: 'POSTS/LOAD_POSTS_REQUEST',
  SUCCESS: 'POSTS/LOAD_POSTS_SUCCESS',
  FAIL: 'POSTS/LOAD_POSTS_FAIL',
};

export const LOAD_POST = {
  REQUEST: 'POSTS/LOAD_POST_REQUEST',
  SUCCESS: 'POSTS/LOAD_POST_SUCCESS',
  FAIL: 'POSTS/LOAD_POST_FAIL',
};

export const LOAD_COMMENTS = {
  REQUEST: 'POSTS/LOAD_COMMENTS_REQUEST',
  SUCCESS: 'POSTS/LOAD_COMMENTS_SUCCESS',
  FAIL: 'POSTS/LOAD_COMMENTS_FAIL',
};

export const SEND_COMMENT = {
  REQUEST: 'POSTS/SEND_COMMENT_REQUEST',
  SUCCESS: 'POSTS/SEND_COMMENT_SUCCESS',
  FAIL: 'POSTS/SEND_COMMENT_FAIL',
};
